New attempt at validating token symbols

diff --git a/.github/workflows/processRequest.yml b/.github/workflows/processRequest.yml
--- a/.github/workflows/processRequest.yml
+++ b/.github/workflows/processRequest.yml
@@ -126,6 +126,12 @@ jobs:
           echo "${{ env.NETWORK }} ${{ env.URL }} ${{ env.ADDRESS }}"
           echo "::error title={Validation failed}::{Missing required fields for adding a token}"
           exit 1
+      - name: Validate symbol
+        if: env.SYMBOL && contains(env.SYMBOL, ' ')
+        run: |
+          echo "${{ env.SYMBOL }}"
+          echo "::error title={Validation failed}::{Symbol cannot contain spaces}" 
+          exit 1
       - name: Validate removeToken
         if: contains(github.event.issue.labels.*.name, 'removeToken') && (!env.NETWORK || !env.REASON || !env.ADDRESS)
         run: |
